package CCASolutions.Calendario.Controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import CCASolutions.Calendario.DTOs.CalendarByYearDTO;
import CCASolutions.Calendario.Services.DownloadService;

/**
 * EN: Endpoints that hand the client a downloadable document. The generation itself is
 * not implemented yet, so both answer 501 until {@link DownloadService} produces bytes.
 * ES: Endpoints que entregan al cliente un documento descargable. La generación en sí
 * todavía no está implementada, de modo que ambos responden 501 mientras
 * {@link DownloadService} no devuelva contenido.
 */
@RestController
@CrossOrigin("*")
@RequestMapping("/api")
public class DownloadController {

	private static final Logger LOG = LoggerFactory.getLogger(DownloadController.class);

	@Autowired
	private DownloadService downloadService;

	/**
	 * EN: Returns the general PDF of the calendar.
	 * ES: Devuelve el PDF general del calendario.
	 *
	 * @return EN: 200 with the document, 501 while it is not implemented, 500 on failure. / ES: 200 con el documento, 501 mientras no esté implementado, 500 si falla.
	 */
	@GetMapping("/getpdf")
	public ResponseEntity<byte[]> getPDF() {

		try {

			// EN: the service result used to be discarded and an empty array always returned
			// ES: el resultado del servicio se descartaba y siempre se devolvía un array vacío
			return this.responder(this.downloadService.getPDF());
		}
		catch(Exception e) {

			LOG.error("Error al generar el PDF", e);
			return new ResponseEntity<>(new byte[0], HttpStatus.INTERNAL_SERVER_ERROR);
		}
	}

	/**
	 * EN: Returns the calendar for one specific VAU year, identified by its eclipeno, meton
	 * and year numbers.
	 * ES: Devuelve el calendario de un año VAU concreto, identificado por sus números de
	 * eclípeno, métono y año.
	 *
	 * @param yearForCalendar EN: identifiers of the requested VAU year. / ES: identificadores del año VAU solicitado.
	 * @return EN: 200 with the document, 501 while it is not implemented, 500 on failure. / ES: 200 con el documento, 501 mientras no esté implementado, 500 si falla.
	 *
	 * EN: The DTO used to arrive as {@code @RequestParam}, and Spring cannot build a complex
	 * object out of a query parameter, so the call always failed.
	 * ES: El DTO llegaba como {@code @RequestParam}: Spring no sabe construir un objeto complejo
	 * a partir de un parámetro de query y la llamada fallaba siempre.
	 */
	@PostMapping("/getcalendar")
	public ResponseEntity<byte[]> getCalendar(@RequestBody CalendarByYearDTO yearForCalendar) {

		try {

			return this.responder(this.downloadService.getCalendarForAYear(yearForCalendar));
		}
		catch(Exception e) {

			LOG.error("Error al generar el calendario", e);
			return new ResponseEntity<>(new byte[0], HttpStatus.INTERNAL_SERVER_ERROR);
		}
	}

	/**
	 * EN: Wraps the generated bytes into an HTTP response, answering 501 when there is no
	 * content because the generation is still pending.
	 * ES: Envuelve los bytes generados en una respuesta HTTP, respondiendo 501 cuando no
	 * hay contenido porque la generación sigue pendiente.
	 *
	 * @param contenido EN: bytes of the document; may be {@code null} or empty. / ES: bytes del documento; admite {@code null} o vacío.
	 * @return EN: 200 with the document, or 501 if there is nothing to send. / ES: 200 con el documento, o 501 si no hay nada que enviar.
	 */
	private ResponseEntity<byte[]> responder(byte[] contenido) {

		if (contenido == null || contenido.length == 0) {

			// EN: document generation is not implemented yet
			// ES: la generación de documentos todavía no está implementada
			return new ResponseEntity<>(new byte[0], HttpStatus.NOT_IMPLEMENTED);
		}

		return new ResponseEntity<>(contenido, HttpStatus.OK);
	}
}
